name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Make build
        run: |
          poetry build
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: targe-${{ steps.tag.outputs.tag }}.tar.gz
          path: dist/targe-${{ steps.tag.outputs.tag }}.tar.gz
      - name: Publish release
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish

